### PR TITLE
Refresh device token

### PR DESCRIPTION
**Pull request by lukabratos**
### What?

Refresh the device token (register it with the Beams service) if it changes.

----
CC @pusher/mobile

### CODE REVIEW

**Comment by lukabratos** [comment]
@luismfonseca shall we change the `register` endpoint too?

**Comment by luismfonseca** [comment]
We have a separate endpoint in Android to refresh the token. The `register` endpoint does not take a device id.

I think we should do the same in for iOS.

**Comment by lukabratos** [comment]
We've identified that some changes will be needed on the backend in order to resolve this issue.
Closing this PR for now, we'll open new one.

**Comment by lukabratos** [comment]
Hi

Unfortunately I cannot give you an accurate estimate for this issue right now.

**Pull request closed without merging**
